<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ingresar ID</name>
   <tag></tag>
   <elementGuidId>e0a38c21-9659-4184-8c08-7d238b6a3805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label='Arrangement Id']&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C1__C1__C1__C1__C1__QUE_995F3082662B26608950008</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Arrangement Id&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>091e0217-263c-4c60-896b-a92885a4234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7603edc0-39e3-43a6-a5b9-769d19aa574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>C1__C1__C1__C1__C1__ENQAAFINDARRANGEMENTAR[1].SEARCHREQUEST[1].FILTERS[1].ARRANGEMENTID[1].OPERAND1</value>
      <webElementGuid>47d3ad0a-833b-4c5e-9a49-4c004ff7d99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C1__C1__C1__C1__C1__QUE_995F3082662B26608950008</value>
      <webElementGuid>c40f356f-0a96-4d1d-b8e4-40a1d16b63c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc-form-control tc-full-answer-width tc-default-input tc-rounded-1  </value>
      <webElementGuid>9690faf0-fe98-431f-b689-8df237993d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a4243dbb-bb32-45eb-b23c-a571b0d14818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doOnFocus('', this.id, '');</value>
      <webElementGuid>a00628fa-f091-4366-9180-375a0a51f5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>if (FORMAT_VALIDATION_TRIGGER == getTriggeredReason() || '' == getTriggeredReason()) {doOnBlur('', this.id);}</value>
      <webElementGuid>7cd14b1b-8b90-4398-8a65-83aa178e0b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return(checkForDefaultButtonAction(event, this, 'C1__C1__C1__C1__C1____X95F3082662B2660 FormButton 14', ''))</value>
      <webElementGuid>91a9bd03-9cee-4062-bddd-3243044dc030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>startJob('', 'onchange', 'C1__C1__C1__C1__C1__QUE_995F3082662B26608950008');var valid = ajaxValidate('servletcontroller', '', '', event, this, false, false,'', ['','tc-error-color','tc-error-color','','tc-error-color','tc-error-color-border','','','tc-error-color  bd-search-filter-error-position tc-fs-m2','responsive-row  tc-global-color tc-row-part {white-space: nowrap}','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-6-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part {white-space: nowrap}','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-6-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part {white-space: nowrap}','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-6-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','']); endJob('', 'onchange', true, 'C1__C1__C1__C1__C1__QUE_995F3082662B26608950008');return valid;</value>
      <webElementGuid>4b1cd9b2-5cdd-4d0c-a468-3866c11adb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9583bac3-d53f-4516-b3a5-99f28b77900c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Arrangement Id</value>
      <webElementGuid>2b45ac97-3b01-4538-bd69-61f77926669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>C1__C1__C1__C1__C1__QUE_995F3082662B26608950008_INFOMESSAGE</value>
      <webElementGuid>3a274268-6f54-49b3-9e48-1e4d1c193b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>script-id</name>
      <type>Main</type>
      <value>EnqAA_FIND_ARRANGEMENT_AR.ARRANGEMENT_ID_SINGLE_OPERAND.TEXT_INPUT</value>
      <webElementGuid>895ddee8-219f-4d61-bd05-dd43475e6fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C1__C1__C1__C1__C1__QUE_995F3082662B26608950008&quot;)</value>
      <webElementGuid>e20a2e32-28ae-4098-adce-eefb969df53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C1__C1__C1__C1__C1__QUE_995F3082662B26608950008']</value>
      <webElementGuid>8c7f581f-7d16-4afa-b042-2a100f51aa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='C1__C1__C1__C1__C1__p4_QUE_995F3082662B26608950008']/input</value>
      <webElementGuid>8ec483ae-44df-4925-8e39-18defec82206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/div[2]/input</value>
      <webElementGuid>e0a33e4d-8b78-4293-8e16-95d6e94614ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'C1__C1__C1__C1__C1__ENQAAFINDARRANGEMENTAR[1].SEARCHREQUEST[1].FILTERS[1].ARRANGEMENTID[1].OPERAND1' and @id = 'C1__C1__C1__C1__C1__QUE_995F3082662B26608950008']</value>
      <webElementGuid>bd4db2ad-e773-44f1-968f-35551279c87d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
