<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cliente</name>
   <tag></tag>
   <elementGuidId>f47226bd-17ed-4f75-b390-905c749a150a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@title='Ingrese Cliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cliente.1&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aec57fc-5d9b-4740-9e96-39b77d1ce04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widgettype</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>c62f0832-b1a2-4444-81ca-e4140e624c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nominalwidgeticonwidthrem</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fa2aff0c-0e2a-48f5-9b2f-12a676678f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd7cb8fc-20c2-4165-8bd9-321fc0de6ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:handleDropdownFieldKeyUpEvent(event,'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1', 'C1__C2__C1__C1__C1__', 'VERSION_FIELD_DROPDOWN','Y','','%CUSTOMER','','AA.ARRANGEMENT.ACTIVITY,BLDR.AA.NEW','CUSTOMER',400,200,'input');</value>
      <webElementGuid>5017f7c6-c45c-4309-b269-371de9f2009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enrilength</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>b0f7351b-f65c-4687-bf9f-79a0481c60d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddheight tc-form-control tc-full-answer-width tc-default-input tc-rounded-1 tc-full-answer-width CUSTOMER</value>
      <webElementGuid>b4cc645e-c31b-4390-85ab-d188c6e7efa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0f90669-729d-4920-9798-59c77c54f762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>C1__C2__C1__C1__C1__VERAAARRANGEMENTACTIVITY_BLDRAANEW[1].VERAAARRANGEMENTACTIVITY_BLDRAANEW_CUSTOMERMVGROUP[1].ELEMENT[1].CUSTOMER</value>
      <webElementGuid>cc826b32-8d6d-41e3-9cf0-9b281a3015e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1</value>
      <webElementGuid>4a13d063-6b12-488a-a0d7-cb5d276ecd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>6ce1a812-a65a-403f-9522-7b3fd15fa9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>68c3a974-bf73-441c-bcf3-8bdcb43b9e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doOnFocus('', this.id, '');  ;setUpFocusValue('',this);</value>
      <webElementGuid>d7cefe94-7edc-4827-b7d8-ec9886c0b217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>resetDropdownFieldEnrichment(this.id);if(!handleDropdownFieldBlurEvent(this.id, this.value)){return false;}if (FORMAT_VALIDATION_TRIGGER == getTriggeredReason() || '' == getTriggeredReason()) {if (! doOnBlur('', this.id)) return false;  startJob('', 'onblur', 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1');if (ajaxValidate('servletcontroller', '', '', event, this, true, false,'', ['','tc-error-color','tc-error-color','','tc-error-color','tc-error-color-border','','','tc-error-color  tc-error-position tc-fs-m2','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon',''])) {ajaxQuestionAction('XB01DE47ED07F805 Question 4_inst1', 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1', false, '', 'servletcontroller', '', true, event, true, true, false); endJob('', 'onblur', true, 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1'); return true;} else {endJob('', 'onblur', false, 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1'); return false;}}</value>
      <webElementGuid>1cd4c48d-5593-4c18-8f57-a0959c35a9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>manageDropdownDismissalOnEnterKey(event);return(checkForDefaultButtonAction(event, this, 'C1__C2__C1__C1__C1__F', ''))</value>
      <webElementGuid>3f0c8ac4-e8c2-4b58-819b-2f06fa21701d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese Cliente</value>
      <webElementGuid>7c78e067-0dc0-4116-b357-5edd835971cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5b498b9-3000-45c8-9385-90db40c763fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>assocappname</name>
      <type>Main</type>
      <value>CUSTOMER</value>
      <webElementGuid>ffd2080d-dff9-498d-959d-33624782e81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>script-id</name>
      <type>Main</type>
      <value>VerAA_ARRANGEMENT_ACTIVITY_BLDR_AA_NEW.CUSTOMER.1.TEXT_INPUT</value>
      <webElementGuid>cca94102-6449-4a8b-bb35-f99c65fc0bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1&quot;)</value>
      <webElementGuid>20f75a7b-357d-40ed-be44-baf160fc57d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1']</value>
      <webElementGuid>afa0dc47-8269-4589-9cff-a326ee881bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddWrapper_C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1']/input</value>
      <webElementGuid>8af02667-fc0b-452b-b58f-4e2910a6d9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>b27f6007-9c5c-4b61-8c9b-c7fa937d9232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'C1__C2__C1__C1__C1__VERAAARRANGEMENTACTIVITY_BLDRAANEW[1].VERAAARRANGEMENTACTIVITY_BLDRAANEW_CUSTOMERMVGROUP[1].ELEMENT[1].CUSTOMER' and @id = 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CUSTOMER--_R1' and @title = 'Ingrese Cliente']</value>
      <webElementGuid>b19bf30a-8633-4980-801d-d0787cca10a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
