<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Moneda</name>
   <tag></tag>
   <elementGuidId>5d51021f-9207-4fc8-b948-ca1fba8099fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@title='Ingrese Moneda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Moneda&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afff831e-c186-4df3-88e0-ee67ba965d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-widgettype</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>2fbf65f3-a8cf-47d2-8fcd-2e345bef6479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nominalwidgeticonwidthrem</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e074b4d7-213a-4106-9c90-19795371c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>565ed551-c763-44d5-9877-37f264441f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>javascript:handleDropdownFieldKeyUpEvent(event,'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--', 'C1__C2__C1__C1__C1__', 'VERSION_FIELD_DROPDOWN','Y','','','','AA.ARRANGEMENT.ACTIVITY,BLDR.AA.NEW','CURRENCY',400,200,'input');</value>
      <webElementGuid>6978e0bf-fe72-40d5-be18-79bddc1848ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enrilength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>3610660b-3a2b-4ca7-b775-82c50a9c77c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddheight tc-form-control tc-full-answer-width tc-default-input tc-rounded-1 tc-full-answer-width CURRENCY</value>
      <webElementGuid>df7c650b-44ae-4803-ac20-509ec2036eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06f6e88a-351f-45a4-aadd-a86b70f2f629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>C1__C2__C1__C1__C1__VERAAARRANGEMENTACTIVITY_BLDRAANEW[1].CURRENCY</value>
      <webElementGuid>23dcae79-8dc3-4910-94c8-df12ee9cbcb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--</value>
      <webElementGuid>62e118bf-0888-4783-b4c0-4e175cf46b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9bd15bdd-1760-43d0-9cdb-1ffaa449541b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7c4bcd53-a296-428a-81b1-d50b24e3699c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doOnFocus('', this.id, '');  ;setUpFocusValue('',this);</value>
      <webElementGuid>54810e05-653c-4eb1-a64c-2470e805f58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>resetDropdownFieldEnrichment(this.id);if(!handleDropdownFieldBlurEvent(this.id, this.value)){return false;}if (FORMAT_VALIDATION_TRIGGER == getTriggeredReason() || '' == getTriggeredReason()) {if (! doOnBlur('', this.id)) return false;  startJob('', 'onblur', 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--');if (ajaxValidate('servletcontroller', '', '', event, this, true, false,'', ['','tc-error-color','tc-error-color','','tc-error-color','tc-error-color-border','','','tc-error-color  tc-error-position tc-fs-m2','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon','','responsive-row  tc-global-color tc-row-part','responsive-column col-full-xs col-3-8-sm col-4-12-md col-4-12-lg col-5-16-xl  tc-question-part tc-bold','tc-mand-part tc-normal-weight','','responsive-column col-full-xs col-5-8-sm col-8-12-md col-8-12-lg col-10-16-xl','tc-form-control tc-full-answer-width','','tc-help-icon',''])) {ajaxQuestionAction('XB01DE47ED07F805 Question 8', 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--', false, '', 'servletcontroller', '', true, event, true, true, false); endJob('', 'onblur', true, 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--'); return true;} else {endJob('', 'onblur', false, 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--'); return false;}}</value>
      <webElementGuid>20604259-a4c0-4773-afd9-6acd54962d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>manageDropdownDismissalOnEnterKey(event);return(checkForDefaultButtonAction(event, this, 'C1__C2__C1__C1__C1__F', ''))</value>
      <webElementGuid>81561e3a-7723-4fdb-8f7b-b4c317610e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ingrese Moneda</value>
      <webElementGuid>d68056e8-02e2-4554-ab99-190a8dfcc40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a1a296e-1fba-4f9d-a339-3ecb65674cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>assocappname</name>
      <type>Main</type>
      <value>CURRENCY</value>
      <webElementGuid>3c91533d-1d8c-4b7f-a110-bf8e10302f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>script-id</name>
      <type>Main</type>
      <value>VerAA_ARRANGEMENT_ACTIVITY_BLDR_AA_NEW.CURRENCY.TEXT_INPUT</value>
      <webElementGuid>258ab05a-e7db-448d-9048-a91fce637fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--&quot;)</value>
      <webElementGuid>2e98470e-40c8-41df-ae57-b39f7a945892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--']</value>
      <webElementGuid>682e414f-a467-4d04-8daa-68aa26c5c19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ddWrapper_C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--']/input</value>
      <webElementGuid>1c9f7609-e68e-489b-b7dc-cf930dfe0374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>457a2ea1-f0fa-4868-8568-99173a8eafd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'C1__C2__C1__C1__C1__VERAAARRANGEMENTACTIVITY_BLDRAANEW[1].CURRENCY' and @id = 'C1__C2__C1__C1__C1__QUE_--AA-ARRANGEMENT-ACTIVITY--CURRENCY--' and @title = 'Ingrese Moneda']</value>
      <webElementGuid>1bd51181-e90d-4008-ab94-1c0007bd100f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
