<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Validar</name>
   <tag></tag>
   <elementGuidId>507f52c2-0018-4495-a227-731fbe994159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='C1__aa_populate_version_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#C1__aa_populate_version_button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ĨAAPopulate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>27ba65a4-499d-40aa-86e7-a584e1f3637f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AAPopulate</value>
      <webElementGuid>d9ca9a77-d32e-46b2-a2ad-416e1d3bf1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C1__aa_populate_version_button&quot;)/span[1]</value>
      <webElementGuid>54c7f335-02a3-413a-b547-623efa36296c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='C1__aa_populate_version_button']/span</value>
      <webElementGuid>2849f542-f9c4-49e7-b7cd-4f4f31738515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate'])[1]/following::span[1]</value>
      <webElementGuid>2076da40-3f18-4346-b446-9256792a5000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commit'])[1]/following::span[2]</value>
      <webElementGuid>fcc3d037-aa4f-4a95-a0bc-83c6b18db6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hold'])[1]/preceding::span[1]</value>
      <webElementGuid>786734b8-f2bd-454b-9ae6-9d427b1a7180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorise'])[1]/preceding::span[2]</value>
      <webElementGuid>e9a80881-c8cc-4eba-87ea-5100383a07ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AAPopulate']/parent::*</value>
      <webElementGuid>9baaaa62-43be-4769-ade4-b47d6bd4779c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/span</value>
      <webElementGuid>eeff23e7-51d5-47fa-8e5a-fbdbf45e9072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AAPopulate' or . = 'AAPopulate')]</value>
      <webElementGuid>f69f8446-342f-49b3-b550-8d3173c33a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
